CREATE TABLE Student_Info (
    Student_Id BIGINT ,
    First_Name VARCHAR(50),
    Last_Name VARCHAR(50),
    Status VARCHAR(20),
    Subject VARCHAR(50)
);

select * from Student_Info
INSERT INTO Student_Info (Student_Id, First_Name, Last_Name, Status, Subject)
VALUES (1, 'Pratham', 'Bangre', 'Active', 'Computer Science'),
(2, 'Pooja', 'Kamble', 'Active', 'English'),
(3, 'Vikas', 'Jadhav', 'Active', 'Maths'),
(4, 'Snehal', 'Gavande', 'Active', 'Civics'),
(5, 'Rohan', 'Pawar', 'Active', 'History'),
(6, 'Neha', 'Chaudhary', 'Inactive', 'Science2'),
(7, 'Siddharth', 'Desai', 'Active', 'Physics'),
(8, 'Kiran', 'Patil', 'Active', 'Chemistry'),
(9, 'Anjali', 'Joshi', 'Inactive', 'Biology'),
(10, 'Amit', 'Verma', 'Active', 'English'),
(11, 'Rajesh', 'Nair', 'Active', 'Maths'),
(12, 'Komal', 'Bhosale', 'Inactive', 'Civics'),
(13, 'Arjun', 'Kulkarni', 'Active', 'History'),
(14, 'Tanvi', 'Pillai', 'Active', 'Science2'),
(15, 'Saurabh', 'Kumar', 'Inactive', 'Physics'),
(16, 'Manisha', 'Shetty', 'Active', 'Chemistry'),
(17, 'Vivek', 'Thakur', 'Active', 'Biology'),
(18, 'Ritika', 'Mishra', 'Inactive', 'English'),
(19, 'Sagar', 'Mehta', 'Active', 'Maths'),
(20, 'Aishwarya', 'Iyer', 'Active', 'Civics'),
(21, 'Kunal', 'Ghosh', 'Inactive', 'History'),
(22, 'Madhuri', 'Tiwari', 'Active', 'Science2'),
(23, 'Akash', 'Menon', 'Active', 'Physics'),
(24, 'Deepika', 'Kapoor', 'Inactive', 'Chemistry'),
(25, 'Sandeep', 'Malhotra', 'Active', 'Biology'),
(26, 'Rashmi', 'Shah', 'Active', 'English'),
(27, 'Vasant', 'Bajpai', 'Inactive', 'Maths'),
(28, 'Pankaj', 'Rathore', 'Active', 'Civics'),
(29, 'Jyoti', 'Singhania', 'Active', 'History'),
(30, 'Suresh', 'Dubey', 'Inactive', 'Science2'),
(31, 'Priyanka', 'Bose', 'Active', 'Physics'),
(32, 'Harish', 'Rajput', 'Active', 'Chemistry'),
(33, 'Meenakshi', 'Agarwal', 'Inactive', 'Biology'),
(34, 'Ravindra', 'Chopra', 'Active', 'English'),
(35, 'Sonali', 'Dutta', 'Active', 'Maths'),
(36, 'Gopal', 'Pandey', 'Inactive', 'Civics'),
(37, 'Usha', 'Kohli', 'Active', 'History'),
(38, 'Nitin', 'Saxena', 'Active', 'Science2'),
(39, 'Geeta', 'Bansal', 'Inactive', 'Physics'),
(40, 'Mahesh', 'Reddy', 'Active', 'Chemistry'),
(41, 'Shilpa', 'Garg', 'Active', 'Biology');
