CREATE TABLE Student_Info (
    Student_Id BIGINT PRIMARY KEY,
    First_Name VARCHAR(50),
    Last_Name VARCHAR(50),
    Status VARCHAR(20),
    Subject VARCHAR(50)
);

select * from Student_Info
INSERT INTO Student_Info (Student_Id, First_Name, Last_Name, Status, Subject)
VALUES (1, 'Pratham', 'Bangre', 'Active', 'Computer Science'),
(2, 'Gaurav', 'Shelure', 'Active', 'English'),
(3, 'Aryan', 'Deshmukh', 'Active', 'Maths'),
(4, 'Sneha', 'Patil', 'Active', 'Civics'),
(5, 'Rohit', 'Sharma', 'Active', 'History'),
(6, 'Ananya', 'Joshi', 'Inactive', 'Science2'),
(7, 'Amit', 'Verma', 'Active', 'Physics'),
(8, 'Priya', 'Singh', 'Active', 'Chemistry'),
(9, 'Kunal', 'Yadav', 'Inactive', 'Biology'),
(10, 'Neha', 'Kumar', 'Active', 'English'),
(11, 'Varun', 'Pillai', 'Active', 'Maths'),
(12, 'Riya', 'Mishra', 'Inactive', 'Civics'),
(13, 'Aarav', 'Kapoor', 'Active', 'History'),
(14, 'Sanya', 'Malhotra', 'Active', 'Science2'),
(15, 'Dhruv', 'Chopra', 'Inactive', 'Physics'),
(16, 'Ishaan', 'Gupta', 'Active', 'Chemistry'),
(17, 'Meera', 'Iyer', 'Active', 'Biology'),
(18, 'Kabir', 'Nair', 'Inactive', 'English'),
(19, 'Tanya', 'Bose', 'Active', 'Maths'),
(20, 'Aditya', 'Rathore', 'Active', 'Civics'),
(21, 'Sakshi', 'Chatterjee', 'Inactive', 'History'),
(22, 'Harsh', 'Pandey', 'Active', 'Science2'),
(23, 'Soham', 'Dutta', 'Active', 'Physics'),
(24, 'Pooja', 'Rajput', 'Inactive', 'Chemistry'),
(25, 'Rudra', 'Mehta', 'Active', 'Biology'),
(26, 'Anushka', 'Reddy', 'Active', 'English'),
(27, 'Ritik', 'Thakur', 'Inactive', 'Maths'),
(28, 'Dev', 'Shetty', 'Active', 'Civics'),
(29, 'Ira', 'Agarwal', 'Active', 'History'),
(30, 'Samarth', 'Kohli', 'Inactive', 'Science2'),
(31, 'Nidhi', 'Menon', 'Active', 'Physics'),
(32, 'Yash', 'Shah', 'Active', 'Chemistry'),
(33, 'Simran', 'Garg', 'Inactive', 'Biology'),
(34, 'Jay', 'Bansal', 'Active', 'English'),
(35, 'Swati', 'Tiwari', 'Active', 'Maths'),
(36, 'Raj', 'Kulkarni', 'Inactive', 'Civics'),
(37, 'Snehal', 'Desai', 'Active', 'History'),
(38, 'Atharva', 'Ghosh', 'Active', 'Science2'),
(39, 'Mahima', 'Saxena', 'Inactive', 'Physics'),
(40, 'Arjun', 'Dubey', 'Active', 'Chemistry'),
(41, 'Kritika', 'Shinde', 'Active', 'Biology');
