CREATE TABLE Courses (
    Course_Id INT PRIMARY KEY,
    Course_Name VARCHAR(100),
    Instructor VARCHAR(100),
    Credits INT,
    Department VARCHAR(100)
);

select * from Courses
INSERT INTO Courses (Course_Id, Course_Name, Instructor, Credits, Department) VALUES
(1, 'Database Systems', 'Dr. Smith', 4, 'Computer Science'),
(2, 'Linear Algebra', 'Dr. Johnson', 3, 'Mathematics'),
(3, 'World History', 'Dr. Brown', 3, 'History'),
(4, 'Organic Chemistry', 'Dr. Taylor', 4, 'Chemistry'),
(5, 'Microeconomics', 'Dr. Anderson', 3, 'Economics'),
(6, 'Machine Learning', 'Dr. Wilson', 4, 'Computer Science'),
(7, 'Calculus II', 'Dr. Adams', 3, 'Mathematics'),
(8, 'Modern Physics', 'Dr. Nelson', 4, 'Physics'),
(9, 'Macroeconomics', 'Dr. Carter', 3, 'Economics'),
(10, 'Environmental Science', 'Dr. Scott', 3, 'Environmental Studies'),
(11, 'Artificial Intelligence', 'Dr. Hall', 4, 'Computer Science'),
(12, 'Discrete Mathematics', 'Dr. Evans', 3, 'Mathematics'),
(13, 'Political Science', 'Dr. White', 3, 'Political Science'),
(14, 'Inorganic Chemistry', 'Dr. Harris', 4, 'Chemistry'),
(15, 'Computer Networks', 'Dr. Clark', 4, 'Computer Science'),
(16, 'Thermodynamics', 'Dr. Lewis', 4, 'Mechanical Engineering'),
(17, 'Shakespearean Literature', 'Dr. Robinson', 3, 'English'),
(18, 'Biochemistry', 'Dr. Walker', 4, 'Biology'),
(19, 'Probability & Statistics', 'Dr. Allen', 3, 'Mathematics'),
(20, 'Software Engineering', 'Dr. Young', 4, 'Computer Science'),
(21, 'Astronomy', 'Dr. King', 3, 'Physics'),
(22, 'Marketing Principles', 'Dr. Wright', 3, 'Business'),
(23, 'Data Structures', 'Dr. Green', 4, 'Computer Science'),
(24, 'Cybersecurity', 'Dr. Baker', 4, 'Computer Science'),
(25, 'Ethical Hacking', 'Dr. Gonzalez', 4, 'Computer Science'),
(26, 'Quantum Mechanics', 'Dr. Turner', 4, 'Physics'),
(27, 'Genetics', 'Dr. Phillips', 4, 'Biology'),
(28, 'Public Speaking', 'Dr. Campbell', 3, 'Communications'),
(29, 'Game Development', 'Dr. Parker', 4, 'Computer Science'),
(30, 'Mobile App Development', 'Dr. Martinez', 4, 'Computer Science'),
(31, 'Entrepreneurship', 'Dr. Mitchell', 3, 'Business'),
(32, 'Financial Accounting', 'Dr. Perez', 3, 'Finance'),
(33, 'Embedded Systems', 'Dr. Roberts', 4, 'Electrical Engineering'),
(34, 'Digital Signal Processing', 'Dr. Edwards', 4, 'Electrical Engineering'),
(35, 'Artificial Neural Networks', 'Dr. Collins', 4, 'Computer Science'),
(36, 'Control Systems', 'Dr. Stewart', 4, 'Electrical Engineering'),
(37, 'Human-Computer Interaction', 'Dr. Morris', 3, 'Computer Science'),
(38, 'Philosophy of Mind', 'Dr. Rogers', 3, 'Philosophy'),
(39, 'Cloud Computing', 'Dr. Reed', 4, 'Computer Science'),
(40, 'Blockchain Technology', 'Dr. Cook', 4, 'Computer Science');
